[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/xtgo/set"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
